version: "3"

services:
  web:
    build: docker/web
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
    container_name: "myapp-app"
    command: mix phx.server
    working_dir: "/myapp"
    volumes:
      - ./:/myapp:cached
      # exclude volumes
      - /myapp/.git
      - /myapp/.idea
      - /myapp/docker
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: "myapp-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      DB_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
