version: "3"
services:
  app:
    build: .
    working_dir: /app
    command: yarn serve
    ports:
      - 1234:8080
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      # 「docker-compose run app yarn cache dir」で表示されたcacheディレクトリを指定する
      # - yarn-cache:/usr/local/share/.cache/yarn/v番号
      - yarn-cache:/usr/local/share/.cache/yarn/v6
    stdin_open: true
    tty: true

volumes:
  yarn-cache:
  node_modules:
